baseURL: https://lillehammerpistolklubb.no
languageCode: nb-no
title: Lillehammer pistolklubb
theme: papermod
pluralizeListTitles: false
defaultContentLanguage: nb
menu:
  main:
    - name: Om oss
      url: /om-oss
      weight: 1
    - name: Kurs
      url: /kurs
      weight: 2
    - name: Nyheter
      url: /nyheter
      weight: 3
    - name: Priser
      url: /priser
      weight: 4
    - name: Terminliste
      url: /terminliste
      weight: 5
    - name: Kontakt
      url: /kontakt
      weight: 6
    - name: Kart
      url: /kart
      weight: 7
    - name: Lenker
      url: /lenker
      weight: 8
    - name: Søk
      url: /søk
      weight: 9
params:
  label:
    icon: images/icon.png
  dateFormat: :date_long
  googleMapsKey: AIzaSyDpVZFx5Lmh9fYSlm7hCMDhylB-9Cbnl_M
  defaultTheme: auto
  disableThemeToggle: true
  homePostListTitle:
    title: Siste nytt
    url: /nyheter
  profileMode:
    enabled: true
    title: Lillehammer pistolklubb
    imageUrl: images/logo.png
    subtitle: |
      Stiftet 9. oktober 1951
  socialIcons:
    - name: facebook
      url: https://www.facebook.com/groups/247933992318641
  assets:
    favicon: images/icon.png
    favicon16x16: images/icon.png
    favicon32x32: images/icon.png
    apple_touch_icon: images/icon.png
    safari_pinned_tab: images/icon.png
    theme_color: '#ffffff'
    msapplication_TileColor: '#ffffff'
  cover:
    hiddenInList: true
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
