baseURL: https://lillehammerpistolklubb.no
languageCode: nb-no
title: Lillehammer Pistolklubb
theme: papermod
pluralizeListTitles: false
menu:
  main:
    - name: Om oss
      url: /om-oss
      weight: 1
    - name: Nyheter
      url: /nyheter
      weight: 2
    - name: Priser
      url: /priser
      weight: 3
    - name: Terminliste
      url: /terminliste
      weight: 4
    - name: Kontakt
      url: /kontakt
      weight: 5
    - name: Kart
      url: /kart
      weight: 6
    - name: Lenker
      url: /lenker
      weight: 7
    - name: Søk
      url: /søk
      weight: 8
params:
  googleMapsKey: AIzaSyDpVZFx5Lmh9fYSlm7hCMDhylB-9Cbnl_M
  defaultTheme: auto
  disableThemeToggle: true
  profileMode:
    enabled: true
    title: Lillehammer Pistolklubb
    imageUrl: images/logo.png
    subtitle: |
      Stiftet 9. oktober 1951
  socialIcons:
    - name: facebook
      url: https://www.facebook.com/groups/247933992318641
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
