name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: cachix/install-nix-action@v31
      - run: nix build
      - run: |
          set -e
          id_rsa=$(mktemp)
          chmod 600 $id_rsa
          echo "${{ secrets.SSH_KEY }}" > $id_rsa
          rsync --delete --chmod=D755,F644 -vrLe "ssh -i $id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./result/ "${{ secrets.SSH_TARGET }}:${{ secrets.SSH_WEBROOT }}"
          ssh -i $id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ secrets.SSH_TARGET }}" cache-purge
