name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: jakejarvis/hugo-build-action@v0.105.0
      - shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -u "${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }}" "${{ secrets.FTP_HOST }}" -e "mirror -ceRX '.*' '${{ secrets.FTP_PATH }}' . ; quit"
