name: Production

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - name: Build
        run: nix build
      - name: Deploy
        run: |
          set -e
          id_rsa=$(mktemp)
          chmod 600 $id_rsa
          echo "${{ secrets.SSH_KEY }}" > $id_rsa
          ssh -i $id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ secrets.SSH_TARGET }}" -- 'cd "${{ secrets.SSH_WEBROOT }}" && rm -vrf * .*'
          rsync --delete --chmod=D755,F644 -vrLe "ssh -i $id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./result/ "${{ secrets.SSH_TARGET }}:${{ secrets.SSH_WEBROOT }}"
          ssh -i $id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ secrets.SSH_TARGET }}" cache-purge
